#pragma once
#include "TypeLibrary/Public/TypeLibrary.h"

EENUM()
enum ENGINE_CLIENT_API eCharacterState 
{
    CHAR_STATE_IDLE,
    CHAR_STATE_WALK,
    CHAR_STATE_RUN,
    CHAR_STATE_JUMP,
    CHAR_STATE_CLIMB,
    CHAR_STATE_POST_CLIMB,
    CHAR_STATE_VAULT,
    CHAR_STATE_SWIM,
    CHAR_STATE_ROTATE,
    CHAR_STATE_POST_ROTATE,
    CHAR_STATE_FALL,
    CHAR_STATE_ATTACK,
    CHAR_STATE_HIT,
    CHAR_STATE_DIE,
    CHAR_STATE_MAX
};